version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-net
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres
    environment:
      POSTGRES_SERVER: postgres
      BACKEND_CORS_ORIGINS: "http://frontend,http://frontend:5173,https://frontend,https://frontend:5173"
    networks:
      - project-net
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - project-net
    environment:
      VITE_API_URL: http://backend:8000
  adminer:
    image: dockette/adminer
    container_name: adminer
    restart: always
    depends_on:
      - postgres
    networks:
      - project-net
    ports:
      - "8080:80"
networks:
  project-net:
volumes:
  postgres_data:
